### ISSUE TITLE
Python 2.7?

### ISSUE THREAD

**Issue by amdegroot** [jmalla588/simpleRSA#1]
Hi, I stumbled upon this code, but I only have Python2.  Is there any chance you plan on making it backwards compatible?

**Comment by jmalla588** [comment]
Here you go! [Download Python 3](https://www.python.org/downloads/)

**Comment by amdegroot** [comment]
Ah, thanks for clearing that up. Closing this issue for now, but you might want to consider supporting environments other than your own...
